name: Fail on Dummy Component

on:
  push:
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Fail if DummyComponent.cmp exists
      run: |
          if [[ -n $(find ./ -name 'DummyComponent.cmp') ]]; then
              echo "Error: DummyComponent.cmp found!"
          fi
