name: Custom Metadata Checks

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - integration
        paths:
            - 'force-app/**'

jobs:
    quality-checks:
        name: 'Run Quality Checks'
        uses: 'Szandor72/devops-center-actions/.github/workflows/quality-checks.yml@main'
