name: Code Scans with SF(DX) Scanner

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - integration
        paths:
            - 'force-app/**'

jobs:
    sfdx-scanner:
        name: 'SFDX Scanner'
        uses: 'Szandor72/devops-center-actions/.github/workflows/sfdx-scanner.yml@main'
        secrets: inherit
